apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
  labels:
    app: auth
type: Opaque
data:
  # postgres://authuser:authpass@auth-db:5432/authdb
  url: cG9zdGdyZXM6Ly9hdXRodXNlcjphdXRocGFzc0BhdXRoLWRiOjU0MzIvYXV0aGRi
  # dev-secret-change-in-prod
  jwt: ZGV2LXNlY3JldC1jaGFuZ2UtaW4tcHJvZA==

---

apiVersion: v1
kind: Secret
metadata:
  name: catalog-db-secret
  labels:
    app: catalog
type: Opaque
data:
  # postgres://cataloguser:catalogpass@catalog-db:5432/catalogdb
  url: cG9zdGdyZXM6Ly9jYXRhbG9ndXNlcjpjYXRhbG9ncGFzc0BjYXRhbG9nLWRiOjU0MzIvY2F0YWxvZ2Ri
  # dev-secret-change-in-prod
  jwt: ZGV2LXNlY3JldC1jaGFuZ2UtaW4tcHJvZA==
